
version: '3.8'

services:
 
  dbmysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_agenda
    ports:
      - '3306:3306'
  api-agenda:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - dbmysql
    image: agenda-api 
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://dbmysql:3306/db_agenda?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    restart: on-failure
      
    
  
---
