
version: '3.8'

services:
 
  dbmysql:
    container_name: dbmysql
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - my-db:/var/lib/mysql
    
  api-agenda:
    depends_on:
      - dbmysql
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api-agenda
    image: agenda-api
    env_file: ./.env
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - DATABASE_URL=jdbc:mysql://dbmysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?autoReconnect=true&allowPublicKeyRetrieval=true&sslMode=DISABLED
      - DATABASE_USERNAME=$MYSQLDB_USER
      - DATABASE_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    
 
volumes:
  my-db:
  
    
