
version: '3.8'

services:
  # MySQL
  dbmysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_agenda
    ports:
      - '3306:3306'
    networks:
      springboot-mysql-agenda:
  api-agenda:
    build:
      context: ./
      dockerfile: Dockerfile
    image: agenda-api
    depends_on:
      - dbmysql
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://dbmysql:3306/db_agenda?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    networks:
      springboot-mysql-agenda:
    restart: on-failure

networks:
    springboot-mysql-agenda:
      
    
  
---
